src/objects/ErrorsCatalogue__mdt.object
<CustomObject>
    <description>This Custom Metadata Type is meant to store Application Wide Error Messages, Contact Info etc against a pre decided unique error code generated by the Error Type(Custom or Standard) so that the errors can be logged in with some relevant and consistent Info across the App and will facilitate Admin/Devs to get into an exception quickly just with a unique code showed to the end user along with the message designated in that particular case. Please note that this unique code will be generated at runtime when the exception is being handled and if it does not match against any of the pre decided error codes in the Error Catalogue, a common info would be displayed to the user along with the Exception Code. Exception Code is basically the unique Id of Error Log Object record.</description>
    <fields>
        <fullName>BusinessContact__c</fullName>
        <description>The first business point of Contact.</description>
        <inlineHelpText>Enter the the first business point of Contact for your error. Can be a combination of any of this in this format &lt;Name&gt;-&lt;Contact Number&gt;-&lt;Email&gt;. This field is optional.</inlineHelpText>
        <label>BusinessContact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndUserMessageGenerator__c</fullName>
        <defaultValue>&apos;Shell_CommonErrMsgGenerator&apos;</defaultValue>
        <description>Name of the class that generates the End User Exception Message and implements the Shell_EndUserExcptnMsgGnrtnInterface.</description>
        <inlineHelpText>Provide the name of the class that generates the End User Exception Message and implements the Shell_EndUserExcptnMsgGnrtnInterface.</inlineHelpText>
        <label>EndUserMessageGenerator</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndUserMessage__c</fullName>
        <description>This field is meant to store end user message.</description>
        <inlineHelpText>Please enter some user friendly one liner code like: &quot;A problem occurred. Please contact your CRC&quot;.
            Should not be more than 255 characters including the spaces.</inlineHelpText>
        <label>EndUserMessage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExceptionCode__c</fullName>
        <description>The type of exception will act as exception code on Force.com platform.</description>
        <inlineHelpText>The type of exception will act as exception code on Force.com platform like DMLException, NullPointerException etc.</inlineHelpText>
        <label>ExceptionCode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FunctionalArea__c</fullName>
        <label>FunctionalArea</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <defaultValue>&apos;en&apos;</defaultValue>
        <description>This field would be useful if the org needs internationalization in future. Currently not required. This would be the language Code like en for any kind of English.</description>
        <inlineHelpText>Enter the Language Code eg. &apos;en&apos; for now until internationalization is not there.</inlineHelpText>
        <label>Language</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <description>The severity of the Exception.</description>
        <inlineHelpText>How severe you think this Exception is, i.e. Low, Medium etc.</inlineHelpText>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                    <default>true</default>
                    <label>High</label>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Fatal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TechnicalContact__c</fullName>
        <description>The first technical point of Contact Info, can be used for logging and displaying to the end user as well.</description>
        <inlineHelpText>Enter the first technical point of Contact Info for your error. Can be a combination of any of this in this format &lt;Name&gt;-&lt;Contact Number&gt;-&lt;Email&gt;. This field is again optional.</inlineHelpText>
        <label>TechnicalContact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ErrorsCatalogue</label>
    <pluralLabel>ErrorsCatalogues</pluralLabel>
</CustomObject>

src/objects/SFLoggingSettings__mdt.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LogLevel__c</fullName>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                    <default>true</default>
                    <label>Info</label>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SFLogging Settings</label>
    <pluralLabel>SFLogging Settings</pluralLabel>
</CustomObject>

src/objects/SystemLog__c.object
<CustomObject>
    <description>An object to capture system logs.</description>
    <fields>
        <fullName>ExceptionType__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FunctionalArea__c</fullName>
        <description>An optional field to mark the functional area</description>
        <label>Functional Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogLevel__c</fullName>
        <description>Used to store the log level</description>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warn</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LoggedDateTime__c</fullName>
        <description>A field to store the exact date time at the which the log is recorded. Please note that this can be different than the log creation date(standard field).</description>
        <label>Logged Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Optional field to store some dev specific message provided by dev himself.</description>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SessionId__c</fullName>
        <description>The field to store the session Id in which the log is generated.</description>
        <label>Session Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceClassName__c</fullName>
        <description>Class from which the log is generated.</description>
        <label>Source Class Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceMethodName__c</fullName>
        <description>The method from which the log oiriginates</description>
        <label>Source Method Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>System Log</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoggingService.cls
/*Service Class to perform logging*/
public class LoggingService {

    private final String FALLBACK_EXCEPTION = 'FallbackException';
    private final String FIELD_FOR_CONDITION = 'ExceptionCode__c';
    
    @testVisible
    private static LogCache logCache;
    @testVisible
    private static Set<String> logTypes;

    public LoggingService() {
        logCache = new LogCache();
        logTypes = new Set<String>();
        for(SFLoggingSettings__mdt logSetting : [Select LogLevel__c FROM SFLoggingSettings__mdt WHERE IsActive__c = TRUE]) {
            logTypes.add(logSetting.LogLevel__c);
        }
        
    }
    
    public void log(String sourceClass, String sourceMethod, String functionalArea,
            LogType logType, Object data) {
        log(sourceClass, sourceMethod, functionalArea,
            '', logType, data);
    }

    public void log(String sourceClass, String sourceMethod, String functionalArea, 
        String message, LogType logType) {
        log(sourceClass, sourceMethod, functionalArea,
            message, logType, null);
    }

    public void log(String sourceClass, String sourceMethod, String functionalArea,
            LogType logType) {
        log(sourceClass, sourceMethod, functionalArea,
            '', logType, null);
    }

    public void log(String sourceClass, String sourceMethod, String functionalArea, 
        String message, LogType logType, Object data) {
        if(logTypes.contains(logType.name())) {
            logCache.addLogInfo(new SystemLog__c(SourceClassName__c = sourceClass,
            SourceMethodName__c = sourceMethod,
            FunctionalArea__c = functionalArea,
            Message__c = message,
            LogLevel__c = logType.name(),
            SessionId__c = UserInfo.getSessionId(),
            LoggedDateTime__c = System.now()), data);
        }
    }

    
    public String logException(Exception excptn, String sourceClass, String sourceMethod, String functionalArea, 
        Boolean useErrCtlg) {
        if(logTypes.contains(LogType.Error.name())) {
            logCache.addLogInfo(new SystemLog__c(SourceClassName__c = sourceClass,
                SourceMethodName__c = sourceMethod,
                FunctionalArea__c = functionalArea,
                Message__c = excptn.getMessage(),
                LogLevel__c = LogType.Error.name(),
                ExceptionType__c = excptn.getTypeName(),
                SessionId__c = UserInfo.getSessionId(),
                LoggedDateTime__c = System.now()), excptn.getStackTraceString());
            Id logId = logCache.commitAndFlushLogs();
            if(useErrCtlg) {
                ErrorsCatalogue__mdt errorCatalogueItem = getErrorsCatalogueData(excptn, sourceClass);
                LogCache.ErrorInfo errInfo = new LogCache.ErrorInfo(errorCatalogueItem.EndUserMessage__c, logId,
                        errorCatalogueItem.TechnicalContact__c, errorCatalogueItem.BusinessContact__c,
                        errorCatalogueItem.EndUserMessageGenerator__c, errorCatalogueItem.Severity__c);
                return errInfo.userFriendlyMsg;
            }
            return logId;
        }
        else {
            return '';
        }
    }

	public void commitLogs() {
		logCache.commitAndFlushLogs();
	}

	public void commitLogsAsync() {
        AsyncLoggingService asyncLogingJob = new AsyncLoggingService(logCache);
        System.enqueueJob(asyncLogingJob);
	}

    @testVisible
	private ErrorsCatalogue__mdt getErrorsCatalogueData(Exception excptn, String sourceClass) {
		//Language Based Error Catalogue Logic still needs to be added/developed
        List<ErrorsCatalogue__mdt> errorCatalogueItemsList = (List<ErrorsCatalogue__mdt>)queryErrorsCatalogue(excptn.getTypeName());
        if(errorCatalogueItemsList.isEmpty()) {
            errorCatalogueItemsList = (List<ErrorsCatalogue__mdt>)queryErrorsCatalogue(FALLBACK_EXCEPTION);
        }
        return errorCatalogueItemsList[0];
	}

    @testVisible
    private List<ErrorsCatalogue__mdt> queryErrorsCatalogue(String excptnCode) {
        return [SELECT
            BusinessContact__c,
            DeveloperName,
            EndUserMessage__c,
            EndUserMessageGenerator__c,
            ExceptionCode__c,
            FunctionalArea__c,
            Id,
            Label,
            Language,
            Language__c,
            MasterLabel,
            NamespacePrefix,
            QualifiedApiName,
            Severity__c,
            TechnicalContact__c
            FROM ErrorsCatalogue__mdt WHERE ExceptionCode__c =: excptnCode];
    }

    public class AsyncLoggingService implements Queueable {
        LogCache localLogCache;
        public AsyncLoggingService(LogCache logCacheInstance) {
            System.debug('logCacheInstance: '+logCacheInstance);
            this.localLogCache = logCacheInstance;
        }

        public void execute(QueueableContext context) {
            this.localLogCache.commitAndFlushLogs();
        }
    }
}