src/objects/ErrorsCatalogue__mdt.object
<CustomObject>
    <description>This Custom Metadata Type is meant to store Application Wide Error Messages, Contact Info etc against a pre decided unique error code generated by the Error Type(Custom or Standard) so that the errors can be logged in with some relevant and consistent Info across the App and will facilitate Admin/Devs to get into an exception quickly just with a unique code showed to the end user along with the message designated in that particular case. Please note that this unique code will be generated at runtime when the exception is being handled and if it does not match against any of the pre decided error codes in the Error Catalogue, a common info would be displayed to the user along with the Exception Code. Exception Code is basically the unique Id of Error Log Object record.</description>
    <fields>
        <fullName>BusinessContact__c</fullName>
        <description>The first business point of Contact.</description>
        <inlineHelpText>Enter the the first business point of Contact for your error. Can be a combination of any of this in this format &lt;Name&gt;-&lt;Contact Number&gt;-&lt;Email&gt;. This field is optional.</inlineHelpText>
        <label>BusinessContact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FunctionalArea__c</fullName>
        <label>FunctionalArea</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>ErrorsCatalogue</label>
    <pluralLabel>ErrorsCatalogues</pluralLabel>
</CustomObject>

src/objects/SystemLog__c.object
<CustomObject>
    <description>An object to capture system logs.</description>
    <fields>
        <fullName>FunctionalArea__c</fullName>
        <description>An optional field to mark the functional area</description>
        <label>Functional Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogLevel__c</fullName>
        <description>Used to store the log level</description>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warn</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SourceClassName__c</fullName>
        <description>Class from which the log is generated.</description>
        <label>Source Class Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceMethodName__c</fullName>
        <description>The method from which the log oiriginates</description>
        <label>Source Method Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>System Log</label>
    <nameField>
        <displayFormat>SL-{0000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoggingServicetest.cls
@isTest
private class LoggingServicetest {

	class TestException extends Exception{}

	class NonRegisteredException extends Exception{}

	@isTest
	static void testLoggingForSingleLogs() {
		LoggingService logService = new LoggingService();
		LoggingService.logTypes = new Set<String>{'Info', 'Warning', 'Error'};
		
		//Test for logging without any extra info and message
		logService.log('TestClass', 'TestMethod', 'Testing1', LogType.Info);
		logService.commitLogs();
		List<SystemLog__c> systemLogRecords = [SELECT LogLevel__c FROM SystemLog__c];
		System.assert(systemLogRecords.size() == 1);
		System.assertEquals('Info', systemLogRecords[0].LogLevel__c, 'Not the expected log level');
        
        //Test for logging with extra info, but without any message
        Object testExtraInfoData = '{"key": "value"}';
		logService.log('TestClass', 'TestMethod', 'Testing2', LogType.Warning, testExtraInfoData);
		System.assertEquals(1, LoggingService.logCache.logInfoList.size());
		logService.commitLogs();
		systemLogRecords = [SELECT SourceClassName__c,
		 (SELECT Id, ParentId FROM Attachments) FROM SystemLog__c WHERE LogLevel__c = 'Warning' and
		 FunctionalArea__c = 'Testing2'];
		System.assertEquals(1, systemLogRecords.size());
		System.assertEquals('TestClass', systemLogRecords[0].SourceClassName__c);
		System.assert(systemLogRecords[0].Attachments.size() == 1);
        
        //Test for logging with message, but without any extra info
		logService.log('TestClass', 'TestMethod', 'Testing3', 'Test Message', LogType.Info);
		logService.commitLogs();
		systemLogRecords = [SELECT SourceMethodName__c
		 FROM SystemLog__c WHERE LogLevel__c = 'Info' AND FunctionalArea__c = 'Testing3'];
		System.assertEquals(1, systemLogRecords.size());
		System.assertEquals('TestMethod', systemLogRecords[0].SourceMethodName__c);
        
        //Test for logging with both message and extra info
        testExtraInfoData = '{"key": "value"}';
		logService.log('TestClass', 'TestMethod', 'Testing4', 'Test Message', LogType.Info, testExtraInfoData);
		logService.commitLogs();
		systemLogRecords = new List<SystemLog__c>();
		systemLogRecords = [SELECT FunctionalArea__c,
		 (SELECT Id, ParentId FROM Attachments) FROM SystemLog__c WHERE LogLevel__c = 'Info'
		 AND FunctionalArea__c = 'Testing4'];
		System.assertEquals(1, systemLogRecords.size());
		System.assertEquals('Testing4', systemLogRecords[0].FunctionalArea__c);
		System.assert(systemLogRecords[0].Attachments.size() == 1);
		

		//Test for logging an exception using error catalogue
        String errorMessage = logService.logException(new TestException(), 'TestClass', 'TestMethod', 'Testing', true);
        ErrorsCatalogue__mdt errorCatlgRecord = logService.getErrorsCatalogueData(new TestException(),
        	'Test Class');
        System.assertEquals('Something went wrong. Please connect with your Admin or '+errorCatlgRecord.BusinessContact__c+'.', errorMessage);

        //Test for logging an exception without using error catalogue
        String logId = logService.logException(new TestException(), 'TestClass', 'TestMethod', 'Testing without Catalogue', false);
        System.assertEquals([SELECT SourceMethodName__c
		 FROM SystemLog__c WHERE LogLevel__c = 'Error' AND FunctionalArea__c = 'Testing without Catalogue' LIMIT 1].Id,
		  logId);
        
        //Test for logging an exception using error catalogue but an exception not registered in error catalogue
        errorMessage = logService.logException(new NonRegisteredException(), 'TestClass', 'TestMethod', 'Testing',
        	true);
        errorCatlgRecord = logService.getErrorsCatalogueData(new NonRegisteredException(),
        	'Test Class');
        System.assertEquals('Something went wrong. Please connect with your Admin or '+errorCatlgRecord.BusinessContact__c+'.', errorMessage);

        //Test for logging exception, when error logging is switched off
	    LoggingService.logTypes = new Set<String>{'Info', 'Warning'};
	    errorMessage = logService.logException(new NonRegisteredException(), 'TestClass', 'TestMethod', 'Testing', 
        	true);
	    System.assertEquals('', errorMessage);
	}

    @isTest
    static void testAsyncLogging() {
        LoggingService logService = new LoggingService();
        LoggingService.logTypes = new Set<String>{'Info', 'Warning', 'Error'};
        logService.log('TestClass', 'TestMethod', 'Logging Async', LogType.Info);
        Test.startTest();
        logService.commitLogsAsync();
        Test.stopTest();
		List<SystemLog__c> systemLogRecords = [SELECT FunctionalArea__c,
		(SELECT Id, ParentId FROM Attachments) FROM SystemLog__c WHERE LogLevel__c = 'Info'
		AND FunctionalArea__c = 'Logging Async'];
		System.assertEquals(1, systemLogRecords.size());
	}

	@isTest
	static void bulkTestLoggingService() {
		//Initializing the logging service
		LoggingService logService = new LoggingService();
		LoggingService.logTypes = new Set<String>{'Info', 'Warning', 'Error'};
		//Logging in bulk
		for(Integer logCount =0; logCount<200; logCount++) {
			//Also logging extra info for half of the records
			if(Math.mod(logCount, 2) == 0) {
				logService.log('TestClass', 'TestMethod', 'Testing', 'Test Message', LogType.Info, '{"key": "value"}');
			}
			else {
				logService.log('TestClass', 'TestMethod', 'Testing', LogType.Info);
			}
		}

		logService.commitLogs();
		System.assertEquals(200, [SELECT Id, (SELECT Id, ParentId FROM Attachments) FROM SystemLog__c].size());
        
        //Calculating the number of attachment records stored as Content Version against a log
		Integer logAttachmentsCount = 0;
		for(SystemLog__c testLog : [SELECT Id, (SELECT Id, ParentId FROM Attachments) FROM SystemLog__c]) {
			if(!testLog.Attachments.isEmpty()) {
				logAttachmentsCount++;
			}
		}
		//Should be half the number of log records, i.e. 100
		System.assertEquals(100, logAttachmentsCount);

	}
}